/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.analysis;

import java.util.*;
import portugol.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACabecalho(ACabecalho node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclaracao(ADeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarDeclaracao(AVarDeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealTipo(ARealTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInteiroTipo(AInteiroTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACaractereTipo(ACaractereTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAUnicaVarLista(AUnicaVarLista node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaVarLista(AListaVarLista node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesVar(ASimplesVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVetorVar(AVetorVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConstDeclaracao(AConstDeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringValor(AStringValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInteiroValor(AInteiroValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealValor(ARealValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACorpo(ACorpo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVazioComandoLista(AVazioComandoLista node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAUnicoComandoLista(AUnicoComandoLista node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaComandoLista(AListaComandoLista node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribuicaoComando(AAtribuicaoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALeiaComando(ALeiaComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEscrevaComando(AEscrevaComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAUnicaExpressaoLista(AUnicaExpressaoLista node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASequenciaExpressaoLista(ASequenciaExpressaoLista node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATermoExpressao(ATermoExpressao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaExpressao(ASomaExpressao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubExpressao(ASubExpressao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFatorTermo(AFatorTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultTermo(AMultTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivTermo(ADivTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdFator(AIdFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInteiroFator(AInteiroFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealFator(ARealFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParentesesFator(AParentesesFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBranco(TBranco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCPrograma(TCPrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCInicio(TCInicio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCFim(TCFim node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCConst(TCConst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCReal(TCReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCInteiro(TCInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCCaractere(TCCaractere node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCLeia(TCLeia node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCEscreva(TCEscreva node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCSe(TCSe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCEntao(TCEntao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCSenao(TCSenao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCFimSe(TCFimSe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCAvalie(TCAvalie node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCCaso(TCCaso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCFimAvalie(TCFimAvalie node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCEnquanto(TCEnquanto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCFaca(TCFaca node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCFimEnquanto(TCFimEnquanto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCRepita(TCRepita node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCAte(TCAte node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCPara(TCPara node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCDe(TCDe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCFimPara(TCFimPara node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCPasso(TCPasso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInteiro(TInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTReal(TReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSoma(TSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSub(TSub node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenor(TMenor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaior(TMaior node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenorIgual(TMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaiorIgual(TMaiorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgual(TIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDif(TDif node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSeta(TSeta node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNao(TNao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTE(TE node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTXor(TXor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgula(TVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoisPontos(TDoisPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoVirgula(TPontoVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAPar(TAPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFPar(TFPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTACol(TACol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFCol(TFCol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTACha(TACha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFCha(TFCha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioLinha(TComentarioLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioAninhado(TComentarioAninhado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFComentarioAninhado(TFComentarioAninhado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
