/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import java.util.*;
import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AAvalieComando extends PComando
{
    private TCAvalie _cAvalie_;
    private TAPar _aPar_;
    private PExpressao _expressao_;
    private TFPar _fPar_;
    private final LinkedList<PCaso> _caso_ = new LinkedList<PCaso>();
    private PCasoSenao _casoSenao_;
    private TCFimAvalie _cFimAvalie_;
    private TPontoVirgula _pontoVirgula_;

    public AAvalieComando()
    {
        // Constructor
    }

    public AAvalieComando(
        @SuppressWarnings("hiding") TCAvalie _cAvalie_,
        @SuppressWarnings("hiding") TAPar _aPar_,
        @SuppressWarnings("hiding") PExpressao _expressao_,
        @SuppressWarnings("hiding") TFPar _fPar_,
        @SuppressWarnings("hiding") List<?> _caso_,
        @SuppressWarnings("hiding") PCasoSenao _casoSenao_,
        @SuppressWarnings("hiding") TCFimAvalie _cFimAvalie_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setCAvalie(_cAvalie_);

        setAPar(_aPar_);

        setExpressao(_expressao_);

        setFPar(_fPar_);

        setCaso(_caso_);

        setCasoSenao(_casoSenao_);

        setCFimAvalie(_cFimAvalie_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AAvalieComando(
            cloneNode(this._cAvalie_),
            cloneNode(this._aPar_),
            cloneNode(this._expressao_),
            cloneNode(this._fPar_),
            cloneList(this._caso_),
            cloneNode(this._casoSenao_),
            cloneNode(this._cFimAvalie_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAvalieComando(this);
    }

    public TCAvalie getCAvalie()
    {
        return this._cAvalie_;
    }

    public void setCAvalie(TCAvalie node)
    {
        if(this._cAvalie_ != null)
        {
            this._cAvalie_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cAvalie_ = node;
    }

    public TAPar getAPar()
    {
        return this._aPar_;
    }

    public void setAPar(TAPar node)
    {
        if(this._aPar_ != null)
        {
            this._aPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aPar_ = node;
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    public TFPar getFPar()
    {
        return this._fPar_;
    }

    public void setFPar(TFPar node)
    {
        if(this._fPar_ != null)
        {
            this._fPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fPar_ = node;
    }

    public LinkedList<PCaso> getCaso()
    {
        return this._caso_;
    }

    public void setCaso(List<?> list)
    {
        for(PCaso e : this._caso_)
        {
            e.parent(null);
        }
        this._caso_.clear();

        for(Object obj_e : list)
        {
            PCaso e = (PCaso) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._caso_.add(e);
        }
    }

    public PCasoSenao getCasoSenao()
    {
        return this._casoSenao_;
    }

    public void setCasoSenao(PCasoSenao node)
    {
        if(this._casoSenao_ != null)
        {
            this._casoSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoSenao_ = node;
    }

    public TCFimAvalie getCFimAvalie()
    {
        return this._cFimAvalie_;
    }

    public void setCFimAvalie(TCFimAvalie node)
    {
        if(this._cFimAvalie_ != null)
        {
            this._cFimAvalie_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cFimAvalie_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cAvalie_)
            + toString(this._aPar_)
            + toString(this._expressao_)
            + toString(this._fPar_)
            + toString(this._caso_)
            + toString(this._casoSenao_)
            + toString(this._cFimAvalie_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cAvalie_ == child)
        {
            this._cAvalie_ = null;
            return;
        }

        if(this._aPar_ == child)
        {
            this._aPar_ = null;
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        if(this._fPar_ == child)
        {
            this._fPar_ = null;
            return;
        }

        if(this._caso_.remove(child))
        {
            return;
        }

        if(this._casoSenao_ == child)
        {
            this._casoSenao_ = null;
            return;
        }

        if(this._cFimAvalie_ == child)
        {
            this._cFimAvalie_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cAvalie_ == oldChild)
        {
            setCAvalie((TCAvalie) newChild);
            return;
        }

        if(this._aPar_ == oldChild)
        {
            setAPar((TAPar) newChild);
            return;
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        if(this._fPar_ == oldChild)
        {
            setFPar((TFPar) newChild);
            return;
        }

        for(ListIterator<PCaso> i = this._caso_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCaso) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._casoSenao_ == oldChild)
        {
            setCasoSenao((PCasoSenao) newChild);
            return;
        }

        if(this._cFimAvalie_ == oldChild)
        {
            setCFimAvalie((TCFimAvalie) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
