/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AConstDeclaracaoDeclaracao extends PDeclaracao
{
    private PConstDeclaracao _constDeclaracao_;

    public AConstDeclaracaoDeclaracao()
    {
        // Constructor
    }

    public AConstDeclaracaoDeclaracao(
        @SuppressWarnings("hiding") PConstDeclaracao _constDeclaracao_)
    {
        // Constructor
        setConstDeclaracao(_constDeclaracao_);

    }

    @Override
    public Object clone()
    {
        return new AConstDeclaracaoDeclaracao(
            cloneNode(this._constDeclaracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstDeclaracaoDeclaracao(this);
    }

    public PConstDeclaracao getConstDeclaracao()
    {
        return this._constDeclaracao_;
    }

    public void setConstDeclaracao(PConstDeclaracao node)
    {
        if(this._constDeclaracao_ != null)
        {
            this._constDeclaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constDeclaracao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constDeclaracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constDeclaracao_ == child)
        {
            this._constDeclaracao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._constDeclaracao_ == oldChild)
        {
            setConstDeclaracao((PConstDeclaracao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
