/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracoesDeclaracoes extends PDeclaracoes
{
    private PDeclaracoes _declaracoes_;
    private PDeclaracao _declaracao_;

    public ADeclaracoesDeclaracoes()
    {
        // Constructor
    }

    public ADeclaracoesDeclaracoes(
        @SuppressWarnings("hiding") PDeclaracoes _declaracoes_,
        @SuppressWarnings("hiding") PDeclaracao _declaracao_)
    {
        // Constructor
        setDeclaracoes(_declaracoes_);

        setDeclaracao(_declaracao_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracoesDeclaracoes(
            cloneNode(this._declaracoes_),
            cloneNode(this._declaracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracoesDeclaracoes(this);
    }

    public PDeclaracoes getDeclaracoes()
    {
        return this._declaracoes_;
    }

    public void setDeclaracoes(PDeclaracoes node)
    {
        if(this._declaracoes_ != null)
        {
            this._declaracoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracoes_ = node;
    }

    public PDeclaracao getDeclaracao()
    {
        return this._declaracao_;
    }

    public void setDeclaracao(PDeclaracao node)
    {
        if(this._declaracao_ != null)
        {
            this._declaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracoes_)
            + toString(this._declaracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracoes_ == child)
        {
            this._declaracoes_ = null;
            return;
        }

        if(this._declaracao_ == child)
        {
            this._declaracao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracoes_ == oldChild)
        {
            setDeclaracoes((PDeclaracoes) newChild);
            return;
        }

        if(this._declaracao_ == oldChild)
        {
            setDeclaracao((PDeclaracao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
