/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracao extends PDeclaracao
{
    private PVarDeclaracaoLista _varDeclaracaoLista_;
    private PConstDeclaracaoLista _constDeclaracaoLista_;

    public ADeclaracao()
    {
        // Constructor
    }

    public ADeclaracao(
        @SuppressWarnings("hiding") PVarDeclaracaoLista _varDeclaracaoLista_,
        @SuppressWarnings("hiding") PConstDeclaracaoLista _constDeclaracaoLista_)
    {
        // Constructor
        setVarDeclaracaoLista(_varDeclaracaoLista_);

        setConstDeclaracaoLista(_constDeclaracaoLista_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracao(
            cloneNode(this._varDeclaracaoLista_),
            cloneNode(this._constDeclaracaoLista_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracao(this);
    }

    public PVarDeclaracaoLista getVarDeclaracaoLista()
    {
        return this._varDeclaracaoLista_;
    }

    public void setVarDeclaracaoLista(PVarDeclaracaoLista node)
    {
        if(this._varDeclaracaoLista_ != null)
        {
            this._varDeclaracaoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDeclaracaoLista_ = node;
    }

    public PConstDeclaracaoLista getConstDeclaracaoLista()
    {
        return this._constDeclaracaoLista_;
    }

    public void setConstDeclaracaoLista(PConstDeclaracaoLista node)
    {
        if(this._constDeclaracaoLista_ != null)
        {
            this._constDeclaracaoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constDeclaracaoLista_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varDeclaracaoLista_)
            + toString(this._constDeclaracaoLista_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varDeclaracaoLista_ == child)
        {
            this._varDeclaracaoLista_ = null;
            return;
        }

        if(this._constDeclaracaoLista_ == child)
        {
            this._constDeclaracaoLista_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varDeclaracaoLista_ == oldChild)
        {
            setVarDeclaracaoLista((PVarDeclaracaoLista) newChild);
            return;
        }

        if(this._constDeclaracaoLista_ == oldChild)
        {
            setConstDeclaracaoLista((PConstDeclaracaoLista) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
