/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AEExpLogicaExpressaoLogica extends PExpressaoLogica
{
    private PExpressaoLogica _expressaoLogica_;
    private TE _e_;
    private PExpsLogicas _expsLogicas_;

    public AEExpLogicaExpressaoLogica()
    {
        // Constructor
    }

    public AEExpLogicaExpressaoLogica(
        @SuppressWarnings("hiding") PExpressaoLogica _expressaoLogica_,
        @SuppressWarnings("hiding") TE _e_,
        @SuppressWarnings("hiding") PExpsLogicas _expsLogicas_)
    {
        // Constructor
        setExpressaoLogica(_expressaoLogica_);

        setE(_e_);

        setExpsLogicas(_expsLogicas_);

    }

    @Override
    public Object clone()
    {
        return new AEExpLogicaExpressaoLogica(
            cloneNode(this._expressaoLogica_),
            cloneNode(this._e_),
            cloneNode(this._expsLogicas_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEExpLogicaExpressaoLogica(this);
    }

    public PExpressaoLogica getExpressaoLogica()
    {
        return this._expressaoLogica_;
    }

    public void setExpressaoLogica(PExpressaoLogica node)
    {
        if(this._expressaoLogica_ != null)
        {
            this._expressaoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoLogica_ = node;
    }

    public TE getE()
    {
        return this._e_;
    }

    public void setE(TE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public PExpsLogicas getExpsLogicas()
    {
        return this._expsLogicas_;
    }

    public void setExpsLogicas(PExpsLogicas node)
    {
        if(this._expsLogicas_ != null)
        {
            this._expsLogicas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expsLogicas_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoLogica_)
            + toString(this._e_)
            + toString(this._expsLogicas_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoLogica_ == child)
        {
            this._expressaoLogica_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._expsLogicas_ == child)
        {
            this._expsLogicas_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoLogica_ == oldChild)
        {
            setExpressaoLogica((PExpressaoLogica) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((TE) newChild);
            return;
        }

        if(this._expsLogicas_ == oldChild)
        {
            setExpsLogicas((PExpsLogicas) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
