/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AExpLogicaExpressaoLogica extends PExpressaoLogica
{
    private PExpsLogicas _expsLogicas_;

    public AExpLogicaExpressaoLogica()
    {
        // Constructor
    }

    public AExpLogicaExpressaoLogica(
        @SuppressWarnings("hiding") PExpsLogicas _expsLogicas_)
    {
        // Constructor
        setExpsLogicas(_expsLogicas_);

    }

    @Override
    public Object clone()
    {
        return new AExpLogicaExpressaoLogica(
            cloneNode(this._expsLogicas_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpLogicaExpressaoLogica(this);
    }

    public PExpsLogicas getExpsLogicas()
    {
        return this._expsLogicas_;
    }

    public void setExpsLogicas(PExpsLogicas node)
    {
        if(this._expsLogicas_ != null)
        {
            this._expsLogicas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expsLogicas_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expsLogicas_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expsLogicas_ == child)
        {
            this._expsLogicas_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expsLogicas_ == oldChild)
        {
            setExpsLogicas((PExpsLogicas) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
