/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class AInteiroTipo extends PTipo
{
    private TCInteiro _cInteiro_;

    public AInteiroTipo()
    {
        // Constructor
    }

    public AInteiroTipo(
        @SuppressWarnings("hiding") TCInteiro _cInteiro_)
    {
        // Constructor
        setCInteiro(_cInteiro_);

    }

    @Override
    public Object clone()
    {
        return new AInteiroTipo(
            cloneNode(this._cInteiro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInteiroTipo(this);
    }

    public TCInteiro getCInteiro()
    {
        return this._cInteiro_;
    }

    public void setCInteiro(TCInteiro node)
    {
        if(this._cInteiro_ != null)
        {
            this._cInteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cInteiro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cInteiro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cInteiro_ == child)
        {
            this._cInteiro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cInteiro_ == oldChild)
        {
            setCInteiro((TCInteiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
