/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class AListaConstDeclaracaoLista extends PConstDeclaracaoLista
{
    private PConstDeclaracaoLista _constDeclaracaoLista_;
    private TPontoVirgula _separacao_;
    private PConstDeclaracao _constDeclaracao_;
    private TPontoVirgula _final_;

    public AListaConstDeclaracaoLista()
    {
        // Constructor
    }

    public AListaConstDeclaracaoLista(
        @SuppressWarnings("hiding") PConstDeclaracaoLista _constDeclaracaoLista_,
        @SuppressWarnings("hiding") TPontoVirgula _separacao_,
        @SuppressWarnings("hiding") PConstDeclaracao _constDeclaracao_,
        @SuppressWarnings("hiding") TPontoVirgula _final_)
    {
        // Constructor
        setConstDeclaracaoLista(_constDeclaracaoLista_);

        setSeparacao(_separacao_);

        setConstDeclaracao(_constDeclaracao_);

        setFinal(_final_);

    }

    @Override
    public Object clone()
    {
        return new AListaConstDeclaracaoLista(
            cloneNode(this._constDeclaracaoLista_),
            cloneNode(this._separacao_),
            cloneNode(this._constDeclaracao_),
            cloneNode(this._final_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaConstDeclaracaoLista(this);
    }

    public PConstDeclaracaoLista getConstDeclaracaoLista()
    {
        return this._constDeclaracaoLista_;
    }

    public void setConstDeclaracaoLista(PConstDeclaracaoLista node)
    {
        if(this._constDeclaracaoLista_ != null)
        {
            this._constDeclaracaoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constDeclaracaoLista_ = node;
    }

    public TPontoVirgula getSeparacao()
    {
        return this._separacao_;
    }

    public void setSeparacao(TPontoVirgula node)
    {
        if(this._separacao_ != null)
        {
            this._separacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separacao_ = node;
    }

    public PConstDeclaracao getConstDeclaracao()
    {
        return this._constDeclaracao_;
    }

    public void setConstDeclaracao(PConstDeclaracao node)
    {
        if(this._constDeclaracao_ != null)
        {
            this._constDeclaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constDeclaracao_ = node;
    }

    public TPontoVirgula getFinal()
    {
        return this._final_;
    }

    public void setFinal(TPontoVirgula node)
    {
        if(this._final_ != null)
        {
            this._final_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._final_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constDeclaracaoLista_)
            + toString(this._separacao_)
            + toString(this._constDeclaracao_)
            + toString(this._final_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constDeclaracaoLista_ == child)
        {
            this._constDeclaracaoLista_ = null;
            return;
        }

        if(this._separacao_ == child)
        {
            this._separacao_ = null;
            return;
        }

        if(this._constDeclaracao_ == child)
        {
            this._constDeclaracao_ = null;
            return;
        }

        if(this._final_ == child)
        {
            this._final_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._constDeclaracaoLista_ == oldChild)
        {
            setConstDeclaracaoLista((PConstDeclaracaoLista) newChild);
            return;
        }

        if(this._separacao_ == oldChild)
        {
            setSeparacao((TPontoVirgula) newChild);
            return;
        }

        if(this._constDeclaracao_ == oldChild)
        {
            setConstDeclaracao((PConstDeclaracao) newChild);
            return;
        }

        if(this._final_ == oldChild)
        {
            setFinal((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
