/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class AListaVarDeclaracaoLista extends PVarDeclaracaoLista
{
    private PVarDeclaracaoLista _varDeclaracaoLista_;
    private TPontoVirgula _separacao_;
    private PVarDeclaracao _varDeclaracao_;
    private TPontoVirgula _final_;

    public AListaVarDeclaracaoLista()
    {
        // Constructor
    }

    public AListaVarDeclaracaoLista(
        @SuppressWarnings("hiding") PVarDeclaracaoLista _varDeclaracaoLista_,
        @SuppressWarnings("hiding") TPontoVirgula _separacao_,
        @SuppressWarnings("hiding") PVarDeclaracao _varDeclaracao_,
        @SuppressWarnings("hiding") TPontoVirgula _final_)
    {
        // Constructor
        setVarDeclaracaoLista(_varDeclaracaoLista_);

        setSeparacao(_separacao_);

        setVarDeclaracao(_varDeclaracao_);

        setFinal(_final_);

    }

    @Override
    public Object clone()
    {
        return new AListaVarDeclaracaoLista(
            cloneNode(this._varDeclaracaoLista_),
            cloneNode(this._separacao_),
            cloneNode(this._varDeclaracao_),
            cloneNode(this._final_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaVarDeclaracaoLista(this);
    }

    public PVarDeclaracaoLista getVarDeclaracaoLista()
    {
        return this._varDeclaracaoLista_;
    }

    public void setVarDeclaracaoLista(PVarDeclaracaoLista node)
    {
        if(this._varDeclaracaoLista_ != null)
        {
            this._varDeclaracaoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDeclaracaoLista_ = node;
    }

    public TPontoVirgula getSeparacao()
    {
        return this._separacao_;
    }

    public void setSeparacao(TPontoVirgula node)
    {
        if(this._separacao_ != null)
        {
            this._separacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separacao_ = node;
    }

    public PVarDeclaracao getVarDeclaracao()
    {
        return this._varDeclaracao_;
    }

    public void setVarDeclaracao(PVarDeclaracao node)
    {
        if(this._varDeclaracao_ != null)
        {
            this._varDeclaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDeclaracao_ = node;
    }

    public TPontoVirgula getFinal()
    {
        return this._final_;
    }

    public void setFinal(TPontoVirgula node)
    {
        if(this._final_ != null)
        {
            this._final_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._final_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varDeclaracaoLista_)
            + toString(this._separacao_)
            + toString(this._varDeclaracao_)
            + toString(this._final_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varDeclaracaoLista_ == child)
        {
            this._varDeclaracaoLista_ = null;
            return;
        }

        if(this._separacao_ == child)
        {
            this._separacao_ = null;
            return;
        }

        if(this._varDeclaracao_ == child)
        {
            this._varDeclaracao_ = null;
            return;
        }

        if(this._final_ == child)
        {
            this._final_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varDeclaracaoLista_ == oldChild)
        {
            setVarDeclaracaoLista((PVarDeclaracaoLista) newChild);
            return;
        }

        if(this._separacao_ == oldChild)
        {
            setSeparacao((TPontoVirgula) newChild);
            return;
        }

        if(this._varDeclaracao_ == oldChild)
        {
            setVarDeclaracao((PVarDeclaracao) newChild);
            return;
        }

        if(this._final_ == oldChild)
        {
            setFinal((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
