/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class AListaComandoLista extends PComandoLista
{
    private PComandoLista _comandoLista_;
    private TPontoVirgula _separacao_;
    private PComando _comando_;
    private TPontoVirgula _final_;

    public AListaComandoLista()
    {
        // Constructor
    }

    public AListaComandoLista(
        @SuppressWarnings("hiding") PComandoLista _comandoLista_,
        @SuppressWarnings("hiding") TPontoVirgula _separacao_,
        @SuppressWarnings("hiding") PComando _comando_,
        @SuppressWarnings("hiding") TPontoVirgula _final_)
    {
        // Constructor
        setComandoLista(_comandoLista_);

        setSeparacao(_separacao_);

        setComando(_comando_);

        setFinal(_final_);

    }

    @Override
    public Object clone()
    {
        return new AListaComandoLista(
            cloneNode(this._comandoLista_),
            cloneNode(this._separacao_),
            cloneNode(this._comando_),
            cloneNode(this._final_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaComandoLista(this);
    }

    public PComandoLista getComandoLista()
    {
        return this._comandoLista_;
    }

    public void setComandoLista(PComandoLista node)
    {
        if(this._comandoLista_ != null)
        {
            this._comandoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoLista_ = node;
    }

    public TPontoVirgula getSeparacao()
    {
        return this._separacao_;
    }

    public void setSeparacao(TPontoVirgula node)
    {
        if(this._separacao_ != null)
        {
            this._separacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separacao_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    public TPontoVirgula getFinal()
    {
        return this._final_;
    }

    public void setFinal(TPontoVirgula node)
    {
        if(this._final_ != null)
        {
            this._final_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._final_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoLista_)
            + toString(this._separacao_)
            + toString(this._comando_)
            + toString(this._final_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoLista_ == child)
        {
            this._comandoLista_ = null;
            return;
        }

        if(this._separacao_ == child)
        {
            this._separacao_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        if(this._final_ == child)
        {
            this._final_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoLista_ == oldChild)
        {
            setComandoLista((PComandoLista) newChild);
            return;
        }

        if(this._separacao_ == oldChild)
        {
            setSeparacao((TPontoVirgula) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        if(this._final_ == oldChild)
        {
            setFinal((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
