/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class APrograma extends PPrograma
{
    private PCabecalho _cabecalho_;
    private PDeclaracoes _declaracoes_;
    private PComandos _comandos_;
    private TCFim _cFim_;
    private TPonto _ponto_;

    public APrograma()
    {
        // Constructor
    }

    public APrograma(
        @SuppressWarnings("hiding") PCabecalho _cabecalho_,
        @SuppressWarnings("hiding") PDeclaracoes _declaracoes_,
        @SuppressWarnings("hiding") PComandos _comandos_,
        @SuppressWarnings("hiding") TCFim _cFim_,
        @SuppressWarnings("hiding") TPonto _ponto_)
    {
        // Constructor
        setCabecalho(_cabecalho_);

        setDeclaracoes(_declaracoes_);

        setComandos(_comandos_);

        setCFim(_cFim_);

        setPonto(_ponto_);

    }

    @Override
    public Object clone()
    {
        return new APrograma(
            cloneNode(this._cabecalho_),
            cloneNode(this._declaracoes_),
            cloneNode(this._comandos_),
            cloneNode(this._cFim_),
            cloneNode(this._ponto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrograma(this);
    }

    public PCabecalho getCabecalho()
    {
        return this._cabecalho_;
    }

    public void setCabecalho(PCabecalho node)
    {
        if(this._cabecalho_ != null)
        {
            this._cabecalho_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cabecalho_ = node;
    }

    public PDeclaracoes getDeclaracoes()
    {
        return this._declaracoes_;
    }

    public void setDeclaracoes(PDeclaracoes node)
    {
        if(this._declaracoes_ != null)
        {
            this._declaracoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracoes_ = node;
    }

    public PComandos getComandos()
    {
        return this._comandos_;
    }

    public void setComandos(PComandos node)
    {
        if(this._comandos_ != null)
        {
            this._comandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandos_ = node;
    }

    public TCFim getCFim()
    {
        return this._cFim_;
    }

    public void setCFim(TCFim node)
    {
        if(this._cFim_ != null)
        {
            this._cFim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cFim_ = node;
    }

    public TPonto getPonto()
    {
        return this._ponto_;
    }

    public void setPonto(TPonto node)
    {
        if(this._ponto_ != null)
        {
            this._ponto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ponto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cabecalho_)
            + toString(this._declaracoes_)
            + toString(this._comandos_)
            + toString(this._cFim_)
            + toString(this._ponto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cabecalho_ == child)
        {
            this._cabecalho_ = null;
            return;
        }

        if(this._declaracoes_ == child)
        {
            this._declaracoes_ = null;
            return;
        }

        if(this._comandos_ == child)
        {
            this._comandos_ = null;
            return;
        }

        if(this._cFim_ == child)
        {
            this._cFim_ = null;
            return;
        }

        if(this._ponto_ == child)
        {
            this._ponto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cabecalho_ == oldChild)
        {
            setCabecalho((PCabecalho) newChild);
            return;
        }

        if(this._declaracoes_ == oldChild)
        {
            setDeclaracoes((PDeclaracoes) newChild);
            return;
        }

        if(this._comandos_ == oldChild)
        {
            setComandos((PComandos) newChild);
            return;
        }

        if(this._cFim_ == oldChild)
        {
            setCFim((TCFim) newChild);
            return;
        }

        if(this._ponto_ == oldChild)
        {
            setPonto((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
