/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class APrograma extends PPrograma
{
    private PCabecalho _cabecalho_;
    private PDeclaracao _declaracao_;
    private PCorpo _corpo_;
    private TCFim _cFim_;
    private TPonto _ponto_;

    public APrograma()
    {
        // Constructor
    }

    public APrograma(
        @SuppressWarnings("hiding") PCabecalho _cabecalho_,
        @SuppressWarnings("hiding") PDeclaracao _declaracao_,
        @SuppressWarnings("hiding") PCorpo _corpo_,
        @SuppressWarnings("hiding") TCFim _cFim_,
        @SuppressWarnings("hiding") TPonto _ponto_)
    {
        // Constructor
        setCabecalho(_cabecalho_);

        setDeclaracao(_declaracao_);

        setCorpo(_corpo_);

        setCFim(_cFim_);

        setPonto(_ponto_);

    }

    @Override
    public Object clone()
    {
        return new APrograma(
            cloneNode(this._cabecalho_),
            cloneNode(this._declaracao_),
            cloneNode(this._corpo_),
            cloneNode(this._cFim_),
            cloneNode(this._ponto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrograma(this);
    }

    public PCabecalho getCabecalho()
    {
        return this._cabecalho_;
    }

    public void setCabecalho(PCabecalho node)
    {
        if(this._cabecalho_ != null)
        {
            this._cabecalho_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cabecalho_ = node;
    }

    public PDeclaracao getDeclaracao()
    {
        return this._declaracao_;
    }

    public void setDeclaracao(PDeclaracao node)
    {
        if(this._declaracao_ != null)
        {
            this._declaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracao_ = node;
    }

    public PCorpo getCorpo()
    {
        return this._corpo_;
    }

    public void setCorpo(PCorpo node)
    {
        if(this._corpo_ != null)
        {
            this._corpo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corpo_ = node;
    }

    public TCFim getCFim()
    {
        return this._cFim_;
    }

    public void setCFim(TCFim node)
    {
        if(this._cFim_ != null)
        {
            this._cFim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cFim_ = node;
    }

    public TPonto getPonto()
    {
        return this._ponto_;
    }

    public void setPonto(TPonto node)
    {
        if(this._ponto_ != null)
        {
            this._ponto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ponto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cabecalho_)
            + toString(this._declaracao_)
            + toString(this._corpo_)
            + toString(this._cFim_)
            + toString(this._ponto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cabecalho_ == child)
        {
            this._cabecalho_ = null;
            return;
        }

        if(this._declaracao_ == child)
        {
            this._declaracao_ = null;
            return;
        }

        if(this._corpo_ == child)
        {
            this._corpo_ = null;
            return;
        }

        if(this._cFim_ == child)
        {
            this._cFim_ = null;
            return;
        }

        if(this._ponto_ == child)
        {
            this._ponto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cabecalho_ == oldChild)
        {
            setCabecalho((PCabecalho) newChild);
            return;
        }

        if(this._declaracao_ == oldChild)
        {
            setDeclaracao((PDeclaracao) newChild);
            return;
        }

        if(this._corpo_ == oldChild)
        {
            setCorpo((PCorpo) newChild);
            return;
        }

        if(this._cFim_ == oldChild)
        {
            setCFim((TCFim) newChild);
            return;
        }

        if(this._ponto_ == oldChild)
        {
            setPonto((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
