/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ARealTipo extends PTipo
{
    private TCReal _cReal_;

    public ARealTipo()
    {
        // Constructor
    }

    public ARealTipo(
        @SuppressWarnings("hiding") TCReal _cReal_)
    {
        // Constructor
        setCReal(_cReal_);

    }

    @Override
    public Object clone()
    {
        return new ARealTipo(
            cloneNode(this._cReal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARealTipo(this);
    }

    public TCReal getCReal()
    {
        return this._cReal_;
    }

    public void setCReal(TCReal node)
    {
        if(this._cReal_ != null)
        {
            this._cReal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cReal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cReal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cReal_ == child)
        {
            this._cReal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cReal_ == oldChild)
        {
            setCReal((TCReal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
