/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class ASeComando extends PComando
{
    private TCSe _cSe_;
    private TAPar _aPar_;
    private PExpressaoLogica _expressaoLogica_;
    private TFPar _fPar_;
    private TCEntao _cEntao_;
    private PComandos _comandos_;
    private PSeSenao _seSenao_;
    private TCFimSe _cFimSe_;
    private TPontoVirgula _pontoVirgula_;

    public ASeComando()
    {
        // Constructor
    }

    public ASeComando(
        @SuppressWarnings("hiding") TCSe _cSe_,
        @SuppressWarnings("hiding") TAPar _aPar_,
        @SuppressWarnings("hiding") PExpressaoLogica _expressaoLogica_,
        @SuppressWarnings("hiding") TFPar _fPar_,
        @SuppressWarnings("hiding") TCEntao _cEntao_,
        @SuppressWarnings("hiding") PComandos _comandos_,
        @SuppressWarnings("hiding") PSeSenao _seSenao_,
        @SuppressWarnings("hiding") TCFimSe _cFimSe_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setCSe(_cSe_);

        setAPar(_aPar_);

        setExpressaoLogica(_expressaoLogica_);

        setFPar(_fPar_);

        setCEntao(_cEntao_);

        setComandos(_comandos_);

        setSeSenao(_seSenao_);

        setCFimSe(_cFimSe_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new ASeComando(
            cloneNode(this._cSe_),
            cloneNode(this._aPar_),
            cloneNode(this._expressaoLogica_),
            cloneNode(this._fPar_),
            cloneNode(this._cEntao_),
            cloneNode(this._comandos_),
            cloneNode(this._seSenao_),
            cloneNode(this._cFimSe_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeComando(this);
    }

    public TCSe getCSe()
    {
        return this._cSe_;
    }

    public void setCSe(TCSe node)
    {
        if(this._cSe_ != null)
        {
            this._cSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cSe_ = node;
    }

    public TAPar getAPar()
    {
        return this._aPar_;
    }

    public void setAPar(TAPar node)
    {
        if(this._aPar_ != null)
        {
            this._aPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aPar_ = node;
    }

    public PExpressaoLogica getExpressaoLogica()
    {
        return this._expressaoLogica_;
    }

    public void setExpressaoLogica(PExpressaoLogica node)
    {
        if(this._expressaoLogica_ != null)
        {
            this._expressaoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoLogica_ = node;
    }

    public TFPar getFPar()
    {
        return this._fPar_;
    }

    public void setFPar(TFPar node)
    {
        if(this._fPar_ != null)
        {
            this._fPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fPar_ = node;
    }

    public TCEntao getCEntao()
    {
        return this._cEntao_;
    }

    public void setCEntao(TCEntao node)
    {
        if(this._cEntao_ != null)
        {
            this._cEntao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cEntao_ = node;
    }

    public PComandos getComandos()
    {
        return this._comandos_;
    }

    public void setComandos(PComandos node)
    {
        if(this._comandos_ != null)
        {
            this._comandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandos_ = node;
    }

    public PSeSenao getSeSenao()
    {
        return this._seSenao_;
    }

    public void setSeSenao(PSeSenao node)
    {
        if(this._seSenao_ != null)
        {
            this._seSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seSenao_ = node;
    }

    public TCFimSe getCFimSe()
    {
        return this._cFimSe_;
    }

    public void setCFimSe(TCFimSe node)
    {
        if(this._cFimSe_ != null)
        {
            this._cFimSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cFimSe_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cSe_)
            + toString(this._aPar_)
            + toString(this._expressaoLogica_)
            + toString(this._fPar_)
            + toString(this._cEntao_)
            + toString(this._comandos_)
            + toString(this._seSenao_)
            + toString(this._cFimSe_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cSe_ == child)
        {
            this._cSe_ = null;
            return;
        }

        if(this._aPar_ == child)
        {
            this._aPar_ = null;
            return;
        }

        if(this._expressaoLogica_ == child)
        {
            this._expressaoLogica_ = null;
            return;
        }

        if(this._fPar_ == child)
        {
            this._fPar_ = null;
            return;
        }

        if(this._cEntao_ == child)
        {
            this._cEntao_ = null;
            return;
        }

        if(this._comandos_ == child)
        {
            this._comandos_ = null;
            return;
        }

        if(this._seSenao_ == child)
        {
            this._seSenao_ = null;
            return;
        }

        if(this._cFimSe_ == child)
        {
            this._cFimSe_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cSe_ == oldChild)
        {
            setCSe((TCSe) newChild);
            return;
        }

        if(this._aPar_ == oldChild)
        {
            setAPar((TAPar) newChild);
            return;
        }

        if(this._expressaoLogica_ == oldChild)
        {
            setExpressaoLogica((PExpressaoLogica) newChild);
            return;
        }

        if(this._fPar_ == oldChild)
        {
            setFPar((TFPar) newChild);
            return;
        }

        if(this._cEntao_ == oldChild)
        {
            setCEntao((TCEntao) newChild);
            return;
        }

        if(this._comandos_ == oldChild)
        {
            setComandos((PComandos) newChild);
            return;
        }

        if(this._seSenao_ == oldChild)
        {
            setSeSenao((PSeSenao) newChild);
            return;
        }

        if(this._cFimSe_ == oldChild)
        {
            setCFimSe((TCFimSe) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
