/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class ASequenciaExpressaoLista extends PExpressaoLista
{
    private PExpressaoLista _expressaoLista_;
    private TVirgula _virgula_;
    private PExpressao _expressao_;

    public ASequenciaExpressaoLista()
    {
        // Constructor
    }

    public ASequenciaExpressaoLista(
        @SuppressWarnings("hiding") PExpressaoLista _expressaoLista_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PExpressao _expressao_)
    {
        // Constructor
        setExpressaoLista(_expressaoLista_);

        setVirgula(_virgula_);

        setExpressao(_expressao_);

    }

    @Override
    public Object clone()
    {
        return new ASequenciaExpressaoLista(
            cloneNode(this._expressaoLista_),
            cloneNode(this._virgula_),
            cloneNode(this._expressao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenciaExpressaoLista(this);
    }

    public PExpressaoLista getExpressaoLista()
    {
        return this._expressaoLista_;
    }

    public void setExpressaoLista(PExpressaoLista node)
    {
        if(this._expressaoLista_ != null)
        {
            this._expressaoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoLista_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoLista_)
            + toString(this._virgula_)
            + toString(this._expressao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoLista_ == child)
        {
            this._expressaoLista_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoLista_ == oldChild)
        {
            setExpressaoLista((PExpressaoLista) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
