/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class AUnicaConstDeclaracaoLista extends PConstDeclaracaoLista
{
    private PConstDeclaracao _constDeclaracao_;
    private TPontoVirgula _pontoVirgula_;

    public AUnicaConstDeclaracaoLista()
    {
        // Constructor
    }

    public AUnicaConstDeclaracaoLista(
        @SuppressWarnings("hiding") PConstDeclaracao _constDeclaracao_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setConstDeclaracao(_constDeclaracao_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AUnicaConstDeclaracaoLista(
            cloneNode(this._constDeclaracao_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicaConstDeclaracaoLista(this);
    }

    public PConstDeclaracao getConstDeclaracao()
    {
        return this._constDeclaracao_;
    }

    public void setConstDeclaracao(PConstDeclaracao node)
    {
        if(this._constDeclaracao_ != null)
        {
            this._constDeclaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constDeclaracao_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constDeclaracao_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constDeclaracao_ == child)
        {
            this._constDeclaracao_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._constDeclaracao_ == oldChild)
        {
            setConstDeclaracao((PConstDeclaracao) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
