/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AVarDeclaracaoDeclaracao extends PDeclaracao
{
    private PVarDeclaracao _varDeclaracao_;

    public AVarDeclaracaoDeclaracao()
    {
        // Constructor
    }

    public AVarDeclaracaoDeclaracao(
        @SuppressWarnings("hiding") PVarDeclaracao _varDeclaracao_)
    {
        // Constructor
        setVarDeclaracao(_varDeclaracao_);

    }

    @Override
    public Object clone()
    {
        return new AVarDeclaracaoDeclaracao(
            cloneNode(this._varDeclaracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarDeclaracaoDeclaracao(this);
    }

    public PVarDeclaracao getVarDeclaracao()
    {
        return this._varDeclaracao_;
    }

    public void setVarDeclaracao(PVarDeclaracao node)
    {
        if(this._varDeclaracao_ != null)
        {
            this._varDeclaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDeclaracao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varDeclaracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varDeclaracao_ == child)
        {
            this._varDeclaracao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varDeclaracao_ == oldChild)
        {
            setVarDeclaracao((PVarDeclaracao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
