/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class AVazioVarDeclaracaoLista extends PVarDeclaracaoLista
{

    public AVazioVarDeclaracaoLista()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVazioVarDeclaracaoLista();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioVarDeclaracaoLista(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
