/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class AVunicaVarDeclaracaoLista extends PVarDeclaracaoLista
{
    private PVarDeclaracao _varDeclaracao_;
    private TPontoVirgula _pontoVirgula_;

    public AVunicaVarDeclaracaoLista()
    {
        // Constructor
    }

    public AVunicaVarDeclaracaoLista(
        @SuppressWarnings("hiding") PVarDeclaracao _varDeclaracao_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setVarDeclaracao(_varDeclaracao_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AVunicaVarDeclaracaoLista(
            cloneNode(this._varDeclaracao_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVunicaVarDeclaracaoLista(this);
    }

    public PVarDeclaracao getVarDeclaracao()
    {
        return this._varDeclaracao_;
    }

    public void setVarDeclaracao(PVarDeclaracao node)
    {
        if(this._varDeclaracao_ != null)
        {
            this._varDeclaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDeclaracao_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varDeclaracao_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varDeclaracao_ == child)
        {
            this._varDeclaracao_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varDeclaracao_ == oldChild)
        {
            setVarDeclaracao((PVarDeclaracao) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
