/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCCaso extends Token
{
    public TCCaso()
    {
        super.setText("caso");
    }

    public TCCaso(int line, int pos)
    {
        super.setText("caso");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCCaso(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCCaso(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCCaso text.");
    }
}
