/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCEscreva extends Token
{
    public TCEscreva()
    {
        super.setText("escreva");
    }

    public TCEscreva(int line, int pos)
    {
        super.setText("escreva");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCEscreva(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCEscreva(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCEscreva text.");
    }
}
