/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCFaca extends Token
{
    public TCFaca()
    {
        super.setText("faca");
    }

    public TCFaca(int line, int pos)
    {
        super.setText("faca");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCFaca(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCFaca(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCFaca text.");
    }
}
