/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCFimPara extends Token
{
    public TCFimPara()
    {
        super.setText("fim para");
    }

    public TCFimPara(int line, int pos)
    {
        super.setText("fim para");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCFimPara(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCFimPara(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCFimPara text.");
    }
}
