/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCFimEnquanto extends Token
{
    public TCFimEnquanto()
    {
        super.setText("fim enquanto");
    }

    public TCFimEnquanto(int line, int pos)
    {
        super.setText("fim enquanto");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCFimEnquanto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCFimEnquanto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCFimEnquanto text.");
    }
}
