/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCFimSe extends Token
{
    public TCFimSe()
    {
        super.setText("fim se");
    }

    public TCFimSe(int line, int pos)
    {
        super.setText("fim se");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCFimSe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCFimSe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCFimSe text.");
    }
}
