/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCPara extends Token
{
    public TCPara()
    {
        super.setText("para");
    }

    public TCPara(int line, int pos)
    {
        super.setText("para");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCPara(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCPara(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCPara text.");
    }
}
