/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCPasso extends Token
{
    public TCPasso()
    {
        super.setText("passo");
    }

    public TCPasso(int line, int pos)
    {
        super.setText("passo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCPasso(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCPasso(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCPasso text.");
    }
}
