/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.portugol.node;

import src.portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCRepita extends Token
{
    public TCRepita()
    {
        super.setText("repita");
    }

    public TCRepita(int line, int pos)
    {
        super.setText("repita");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCRepita(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCRepita(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCRepita text.");
    }
}
